use_frameworks!

target 'MultiModelTableViewDataSource_Example' do
  pod 'MultiModelTableViewDataSource', :path => '../'

  target 'MultiModelTableViewDataSource_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
